# Generated by Django 4.1.7 on 2023-03-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('business_name', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
