# Generated by Django 4.1.7 on 2023-03-13 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_myuser_groups_myuser_is_asuperuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_asuperuser',
        ),
    ]
