# Generated by Django 4.1.7 on 2023-03-13 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_myuser_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('website', models.URLField(blank=True, max_length=1024, null=True)),
                ('linkedIn', models.URLField(blank=True, max_length=1024, null=True)),
                ('youtube', models.URLField(blank=True, max_length=1024, null=True)),
                ('instagram', models.URLField(blank=True, max_length=1024, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('designer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
